[package]
name = "kbEngine3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.29"
env_logger = "0.10"
log = "0.4"
wgpu = "0.19.3"
wgpu_text = "0.8.7"
pollster = "0.3"
bytemuck = { version = "1.12", features = [ "derive" ] }
anyhow = "1.0"
cgmath = "0.18"
rand = "0.8.5"
json = "0.12.4"
ab_glyph = "0.2.24"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]